### PR TITLE
Error on timeout

### PR DESCRIPTION
**Pull request by GDay**
- [ ] Add tests

### CODE REVIEW

**Review by jimjag — APPROVED** [review]
LGTM

**Comment by randlet** [comment]
Hi @GDay, just curious if you could comment on why this was change reverted?  We're using Django-q and struggling a bit with how to handle timed out tasks since we would like them to be counted as failures rather than be retried.   

Thanks for picking up this project!

**Comment by GDay** [comment]
Hi @randlet, sure, no problem. The reason why I reverted it was because I hadn't written any tests for this. I wasn't comfortable with putting it in a new release yet. Honestly, it probably shouldn't have gotten merged in the first place. But that was my bad, I should have not marked it as ready for review, but put it as a draft PR here.

I had decided to revert it and add this option when I merge the refactored version (see open PR). The refactored version also allows us to handle timeouts better:
https://github.com/django-q2/django-q2/blob/3b01fc2bd727405aac47e5f83545a746670d8963/django_q/worker.py#L114-L119

I should have a bit of time this week to work on the new version and I think I will have a beta version of that ready by the end of the week.
In the meantime, you could implement something similar, here is that `TimeoutHandler`: https://github.com/django-q2/django-q2/blob/3b01fc2bd727405aac47e5f83545a746670d8963/django_q/exceptions.py
Copy that and wrap that `TimeoutHandler` around the code that might timeout. Then make the django_q2 timeout setting a few seconds bigger than what you pass to the `TimeoutHandler`, so it has time to process the timeout in the task itself. You could then either let the `TimeoutHandler` raise an exception (and thus fail the task) or catch it and raise a different error or do something else. That's up to you.

Hope that helps.

**Comment by randlet** [comment]
Thank you very much for the explanation!  That makes sense and glad to hear that there wasn't something fundamentally broken about handling timeouts as failures.

**Comment by philgyford** [comment]
I'm trying to better handle my tasks that timeout, so they count as failed tasks, rather than exceptions, and have ended up here.

If I have a function I'm running as a task like this, in a `tasks.py`:

```python
def my_task():
    return another_function()
```

I assume I'd wrap your example code around some/all of that? But I'm not sure what to do when an exception occurs. e.g.:

```python
def my_task():
    try:
        with TimeoutHandler(timeout=100): 
            return another_function()
    except (TimeoutException, Exception) as e: 
        # What do I do here?
```

**Comment by GDay** [comment]
@philgyford That's right, but it's kinda up to you what you want to do next. The code looks fine. 

If you want the task to fail, then you could just raise an error there (or just let `TimeoutException` raise). Note that it might retry depending on your [`max_attempts`](https://django-q2.readthedocs.io/en/master/configure.html#max-attempts) setting. 

Alternatively, you could also have it send an email or trigger a webhook to notify you and just let the task finish (so it would be marked as completed and won't retry). A bit hacky, but might work for your usecase.

**Comment by philgyford** [comment]
@GDay Thank you. At the moment I get an email from Sentry about "reincarnated worker Process-da2caf... after timeout" each time, which is several a day, and I'd like them just to be marked as failed tasks in Django Admin, rather than errors.

**Comment by GDay** [comment]
@philgyford  Yeah, then you could just even leave the try catch out and just let it fail hard.

```
with TimeoutHandler(timeout=100): 
    return another_function()
```

Then, to avoid errors in Sentry, you can do something like this (untested but should work):
```
def before_send(event, hint):
    if 'exc_info' in hint:
        exc_exception = hint['exc_info'][1]

        if isinstance(exc_exception, TimeoutException):
            return None

    return event

sentry_sdk.init(before_send=before_send)
```

if you don't have the "max_attempts" value set, then this should mark the tasks failed in admin and not retry (and not notify you through Sentry).

**Comment by philgyford** [comment]
A few months later and I'm finally getting round to this… only to realise that there isn't a `TimeoutException` in the current release.

Is there any way to gracefully handle timeouts in the current release?

**Comment by GDay** [comment]
@philgyford I will try to implement this next week.

What do you mean by "gracefully handle timeouts": what does "gracefully" look like for you?

I am thinking I will add a new configuration option called `on_timeout` (or maybe something better? Any suggestions?). 

Then there are three options for this setting:
- `ignore`. marks it failed, but never retries
- `retry_until_max`, marks it as failed and retries until it hits the "max_attempts" setting
- `retry_until_no_timeout`, retries the task until it doesn't time out (not to be confused with actually failing through another exception), which is default behavior right now I think (so this would be the default for this setting)

Would that work for you?

**Comment by philgyford** [comment]
That sounds good to me, thank you. I think `ignore` would be what I'm looking for personally.

(In case it's of any use/interest… In this case my task is to fetch the RSS feeds of a few blogs. Sometimes a site takes a long time to respond and so the task as a whole times out. But every time a feed is successfully fetched it's marked as such, so I'm happy for this to fail silently – the next time the task is run it will just pick up with the next batch of due feeds.

In theory this shouldn't happen because `number_of_feeds_to_fetch * timeout_passed_to_requests.get()` is less than the timeout I've set for django-q2, but in practice…)

**Comment by GDay** [comment]
@philgyford sorry for the delay on this. I have decided against the approach of a setting. Going forward it will mark all timed out tasks as failed, which is probably the expected behavior for those tasks.
I have created a PR here: https://github.com/django-q2/django-q2/pull/184
Will be merged in the next few days.

This will not fix the error message in sentry for you:

> At the moment I get an email from Sentry about "reincarnated worker Process-da2caf... after timeout" each time, which is several a day, and I'd like them just to be marked as failed tasks in Django Admin, rather than errors.

If you are on the business plan from Sentry, then you could create a filter there to ignore this log message:

image

**Pull request merged**
